name: "Jeanine White"
email: "me@example.com"

social:
  - label: "Twitter"
    href: "https://twitter.com/me"
    icon: "twitter-logo"
  - label: "Twitch"
    href: "https://twitch.tv/me"
    icon: "twitch-logo"
  - label: "GitHub"
    href: "https://github.com/me"
    icon: "github-logo"
  - label: "CodePen"
    href: "https://codepen.io/me"
    icon: "codepen-logo"
  - label: "dribbble"
    href: "https://dribbble.com/me"
    icon: "dribbble-logo"
  - label: "YouTube"
    href: "https://www.youtube.com/@me/"
    icon: "youtube-logo"

footer:
  text: "Designed & Developed in"
  location: "Portland"
